name: GCP Cloud Functions Deploy (Staging)
on:
  push:
    branches:
      - "staging"
jobs:
  build-deploy-cloud-function:
    permissions:
      contents: "read"
      id-token: "write"

    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_CREDS_JSON }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "session-signups-dev"
          entry_point: "HandleSignUp"
          https_trigger_security_level: "secure-always"
          project_id: "operationspark-org"
          region: "us-central1"
          runtime: "go116"
          env_vars: >-
            SLACK_WEBHOOK_URL=${{secrets.SLACK_WEBHOOK_URL}},
            MAIL_DOMAIN=${{secrets.MAIL_DOMAIN}},
            MAILGUN_API_KEY=${{secrets.MAILGUN_API_KEY}},
            GREENLIGHT_WEBHOOK_URL=${{secrets.GREENLIGHT_WEBHOOK_URL}}
      - id: "trigger-url"
        run: 'echo "${{ steps.deploy.outputs.url }}"'
