name: "Signup Service Smoke Test"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
jobs:
  # nektos/act does not ye support resusable workflows
  # Comment this in when running in GitHub Actions
  # https://github.com/nektos/act/issues/826
  # deploy:
  #   uses: ./.github/workflows/deploy.yml
  smoke-test:
    name: "Smoke Test"
    runs-on: ubuntu-latest
    # needs: [deploy]
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Run Signup Smoke Test"
        run: |
          cd cmd/smoke
          go test
